apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: build-and-deploy
spec:
  workspaces:
  - name: shared-workspace
    description: This workspace contains the cloned repo files, so they can be read by the next task.
#  - name: git-credentials
#    description: My ssh credentials
  - name: git-basic-auth
    description: Basic auth for https git repo url
#  - name: git-config
#    description: Contains Git configuration files
  params:
  - name: deployment-name
    type: string
    description: name of the deployment to be patched
  - name: git-url
    type: string
    description: url of the git repo for the code of deployment
  - name: git-revision
    type: string
    description: revision to be used from repo of the code for deployment
    default: main
  - name: IMAGE
    type: string
    description: image to be build from the code
  tasks:
  - name: fetch-repository
    taskRef:
      name: git-clone
      kind: ClusterTask
    workspaces:
    - name: output
      workspace: shared-workspace
#    - name: ssh-directory
#      workspace: git-credentials
    - name: basic-auth
      workspace: git-basic-auth
#    - name: ssh-directory
#      workspace: git-config
#      subPath: .gitconfig
#      mount-path: /etc/gitconfig  # Set the Git config path for the container
    params:
    - name: url
      value: $(params.git-url)
#    - name: subdirectory
#      value: ""
    - name: deleteExisting
      value: "true"
    - name: revision
      value: $(params.git-revision)
  - name: build-image
    taskRef:
      name: buildah
      kind: ClusterTask
    params:
    - name: IMAGE
      value: $(params.IMAGE)
    workspaces:
    - name: source
      workspace: shared-workspace
    runAfter:
    - fetch-repository
  - name: apply-manifests
    taskRef:
      name: apply-manifests
    workspaces:
    - name: source
      workspace: shared-workspace
    runAfter:
    - build-image
  - name: update-deployment
    taskRef:
      name: update-deployment
    params:
    - name: deployment
      value: $(params.deployment-name)
    - name: IMAGE
      value: $(params.IMAGE)
    runAfter:
    - apply-manifests
